packages:
  - "apps/*"
  - "packages/*"

catalogs:
  react:
    react: "^19.2.4"
    react-dom: "^19.2.4"
  
  typescript:
    typescript: "^5.9.3"
    "@types/node": "^25.3.0"
  
  eslint:
    eslint: "^10.0.0"
    "@typescript-eslint/eslint-plugin": "^8.56.0"
    "@typescript-eslint/parser": "^8.56.0"
